apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea-admin-secret.sealedsecret.yaml
  - gitea-db-secret.sealedsecret.yaml
  - gitea-redis.sealedsecret.yaml
  - gitea-runner-secret.sealedsecret.yaml
  - gitea-secrets.sealedsecret.yaml
  - harbor-admin-secret.sealedsecret.yaml
  - harbor-build-user.sealedsecret.yaml
  - harbor-core-internal.sealedsecret.yaml
  - harbor-core-secret.sealedsecret.yaml
  - harbor-jobservice-internal.sealedsecret.yaml
  - harbor-postgres-auth.sealedsecret.yaml
  - harbor-registry-credentials.sealedsecret.yaml
  - harbor-registry-s3.sealedsecret.yaml
  - harbor-robot-gitea.sealedsecret.yaml
  - minio-ca.configmap.yaml
  - minio-ca.sealedsecret.yaml
  - monitoring-pve-exporter.sealedsecret.yaml
  - harbor-valkey.sealedsecret.yaml
  - harborguard-db-secret.sealedsecret.yaml
  - homepage-adguard.sealedsecret.yaml
  - homepage-pbs.sealedsecret.yaml
  - homepage-proxmox.sealedsecret.yaml
  - pgadmin-admin.sealedsecret.yaml
  - renovate-github-token.sealedsecret.yaml
