---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-extra-config
  namespace: apps
spec:
  encryptedData:
    storages.yaml: AgBFBa/5gHPVcfrh6rPlsNc9bEZ/6FCZx95hA4jGG1kVZ/jqVuks8dQQR95hnB3t0CRf19hhZtl15W2mah0dhhrDD9rSbT35ZZrvnFs3oWcYrQ/5xk37iD0q+zjwHSAAP7lkPSuZc9z5FA8u3SkZfzSo+ZbiuFScqPUx/HNnc5rMLt68JkLckdBl0r303myusHjl3rjWc+VF52nhyPFy1PIDpt9vZeOXihAZm/1xJIGf4xcJcj2e2JgRAux7MhfuHrTBPCnOxzZs9ZeKcNqomkLAWQlvnxNiw2C2+OwHr1BPScmo3PKJs4LcYhzB/ZMFw86lJTFPebHYvnhbTYJbzBQOFL2ikMfxE6Y8VIz1OJpp1Ocb4Ohuj7wPySLAZxb0XsMO4tf5nHjWnx3XyUXjAStcJGvWTEUca/mQBZysvJqugLibODRzDaYLUH/12b0OuojVjMnl1E/OaeADFg4GYqP/BP4w9JJJqmyjsMg8lyoUphTNq3Ue/KL60HXXTsAXXmKB5JJ7tu2pfbBsVcZdzrxi5kBdxdpmqwiZFK0mbZmQc/1q95TIUpa/oFjUJ3I2K7L+p/ljIRg8vt63+kaQNlWxxkIdOGQ7li4TgCjvs0A++wdb3iLKcOx6DrZM2uGsC/ZyC+hrBJmCEcKOExgoyrgLS0o4Ts5H2uNgKwj2AXf0y041WxjnihidJck47HbWP/9qMyE+vd+abq53KQoiHRBhdUUl+FF/CfkDZ4ibmEsQ9xLWl7gUZ+7VdochOX8P/uFWVEnWlDw8jqn94IdyqArJcPLudRN3l2YTdwpL85ZhrN8ABQXi5jULt+zvEevC2dJJVZwKKAkOmwKpxdmjYO+rPBACl7dQm0r7/nE0RYz9xtfJdzW3dzEqcYslcSSxQD/NbNC2W27MEYpCZulacYtcGXvpy4efmqvOW0y7G1tRJF5Ye2teSX+4mbG0sQVbBTMbeVwQ9uEf9kjjl8ScyVA7qtyb60uojM5i1xuFMy+k8Awi/VjE++hNIRwtWbKcxEO0pzrfq7p9399FvR4KSSnnW5xdpWMqQY4CbnNnZALCEE3co0bLpVy6Q3rTzBKvkcxI
  template:
    metadata:
      name: netbox-extra-config
      namespace: apps
