k3s_cluster_server_url: "https://10.0.20.20:6443"
k3s_allow_swap: true
tailscale_enable_auto_up: true
tailscale_up_extra_args: "--accept-dns=false"
update_notifier_enabled: true
update_notifier_environment: "m0sh1.cc lab"
update_notifier_on_calendar: "daily"
adguard_bind_host: "0.0.0.0"
adguard_bind_port: 53
adguard_local_domain_name: "m0sh1.cc"
