apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-pve-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apps-root
    app.kubernetes.io/name: prometheus-pve-exporter
    app.kubernetes.io/instance: prometheus-pve-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default

  source:
    repoURL: https://github.com/sm-moshi/infra.git
    targetRevision: main
    path: apps/cluster/prometheus-pve-exporter
    helm:
      releaseName: prometheus-pve-exporter
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
