apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apps-root
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  source:
    repoURL: https://github.com/sm-moshi/infra.git
    targetRevision: main
    path: apps/cluster/traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
