apiVersion: v2
name: prometheus-crds
description: Wrapper chart for Prometheus Operator CRDs
type: application
version: 0.1.0
icon: https://prometheus.io/assets/prometheus_logo_grey.svg

dependencies:
  - name: prometheus-operator-crds
    version: 26.0.0
    repository: https://prometheus-community.github.io/helm-charts
