apiVersion: v2
name: prometheus-crds
description: Prometheus Operator CRDs for kube-prometheus-stack
version: 0.2.0
type: application
# CRDs for prometheus-operator v0.87.1 (as of kube-prometheus-stack 80.14.4)
# These CRDs must be upgraded manually before upgrading kube-prometheus-stack
# See: https://github.com/prometheus-operator/prometheus-operator/releases
appVersion: "0.87.1"
