# SPDX-License-Identifier: MIT-0
---
# Handlers for apt_cacher_ng role
- name: Restart apt-cacher-ng
  ansible.builtin.systemd_service:
    name: "{{ apt_cacher_ng_service }}"
    state: "restarted"
  listen: "Restart apt-cacher-ng"
