k3s_node_labels:
- topology.kubernetes.io/region=m0sh1-cc-lab
- topology.kubernetes.io/zone=pve-02
- topology.m0sh1.cc/pve=pve-02
- topology.m0sh1.cc/storage-nvme=true
- topology.m0sh1.cc/storage-sata-ssd=true

k3s_node_ip: "10.0.20.22"
k3s_node_external_ip:
- "10.0.20.22"

k3s_kubelet_args:
- "provider-id=proxmox://pve-02/211"
