k3s_node_labels:
  - topology.kubernetes.io/region=lab
  - topology.kubernetes.io/zone=pve-01
  - topology.m0sh1.cc/pve=pve-01
  - topology.m0sh1.cc/role=steady
k3s_node_ip: "10.0.0.212"
k3s_node_external_ip:
  - "10.0.0.212"
  - "100.120.6.33"

# k3s_node_taints_remove:
#  - "workload.m0sh1.cc=batch:NoSchedule"
