k3s_node_labels:
- topology.kubernetes.io/region=m0sh1-cc-lab
- topology.kubernetes.io/zone=pve-01
- topology.m0sh1.cc/storage-nvme=true
- topology.m0sh1.cc/storage-sata-ssd=true

k3s_node_ip: "10.0.20.21"
k3s_node_external_ip:
- "10.0.20.21"

k3s_kubelet_args:
- "provider-id=proxmox://pve-01/210"
