swapfile_enabled: true
swapfile_backend: "zvol"
swapfile_zfs_dataset: "rpool/swap"
swapfile_path: "/dev/zvol/rpool/swap"
swapfile_size_mb: 8192
swapfile_swappiness: 25
swapfile_vfs_cache_pressure: 50
swapfile_force_recreate: true

zfs_arc_max_bytes: 2147483648

proxmox_network_enabled: true
proxmox_network_links:
- name: "nic1"
  mac: "00:e0:4c:68:02:56"
proxmox_network_iface_manual:
- "nic1"
proxmox_network_iface_auto:
- "nic1"
proxmox_network_bridge_blocks:
- name: "vmbr1"
  family: "inet"
  method: "static"
  auto: true
  address: 10.0.1.2/30
  options:
    bridge-ports: "nic1"
    bridge-stp: "off"
    bridge-fd: 0
proxmox_network_ethtool_enabled: true
proxmox_network_ethtool_ifaces:
- "nic1"
proxmox_nic_mitigation_enabled: false
