tailscale_authkey: "{{ tailscale_authkey_pve01 }}"
tailscale_enable_auto_up: true
tailscale_force_reauth: true
tailscale_router_enable: true

tailscale_up_extra_args: >
  --ssh=true
  --accept-dns=false
  --accept-routes=false
  --advertise-routes=10.0.10.0/24,10.0.20.0/24,10.0.30.0/24

swapfile_enabled: true
swapfile_backend: "zvol"
swapfile_zfs_dataset: "rpool/swap"
swapfile_path: "/dev/zvol/rpool/swap"
swapfile_size_mb: 4096
swapfile_swappiness: 25
swapfile_vfs_cache_pressure: 50
swapfile_force_recreate: true

zfs_arc_max_bytes: 4294967296

proxmox_network_enabled: true

# Pin names by MAC (ONLY manage in /etc/systemd/network; ignore /usr/local/lib duplicates)
proxmox_network_links:
  - name: "nic0"
    mac: "7c:57:58:26:69:1b"
    match:
      Type: "ether" # onboard LAN
  - name: "nic1"
    mac: "a0:ce:c8:19:e8:e8"
    match:
      Type: "ether" # LAN trunk USB
  - name: "nic2"
    mac: "68:da:73:a0:85:f7"
    match:
      Type: "ether" # WAN USB
  - name: "wlp0"
    mac: "a0:29:42:94:11:aa"
    match:
      Type: "wlan" # onboard wifi
  - name: "wlp1"
    mac: "e8:4e:06:8f:b9:c0"
    match:
      Type: "wlan" # usb wifi
  - name: "wlp2"
    mac: "d0:37:45:79:87:78"
    match:
      Type: "wlan" # usb wifi

proxmox_network_iface_manual:
  - nic0
  - nic1
  - nic2

proxmox_network_bridge_blocks:
  # LAN trunk bridge (before vmbrHP)
  - name: "vmbr0"
    family: "inet"
    method: "static"
    auto: true
    address: "10.0.0.11/24"
    gateway: "10.0.0.1"
    options:
      bridge-ports: "nic1"
      bridge-stp: "off"
      bridge-fd: 0
      bridge-vlan-aware: "yes"
      bridge-vids: "10 20 30"
  - name: "vmbr0.10"
    family: "inet"
    method: "static"
    auto: true
    address: "10.0.10.11/24"
    options:
      vlan-raw-device: "vmbr0"
      vlan-id: "10"
  - name: "vmbr0.20"
    family: "inet"
    method: "static"
    auto: true
    address: "10.0.20.11/24"
    options:
      vlan-raw-device: "vmbr0"
      vlan-id: "20"
  - name: "vmbr0.30"
    family: "inet"
    method: "static"
    auto: true
    address: "10.0.30.11/24"
    options:
      vlan-raw-device: "vmbr0"
      vlan-id: "30"
  # WAN bridge for OPNsense
  - name: "vmbrWAN"
    family: "inet"
    method: "manual"
    auto: true
    options:
      bridge-ports: "nic2"
      bridge-stp: "off"
      bridge-fd: 0

proxmox_network_cleanup_legacy_links: true
proxmox_network_ethtool_enabled: true
proxmox_network_ethtool_offloads_disable:
  - rx
  - tx
  - sg
  - tso
  - gso
  - gro
  - lro
  - rxvlan
  - txvlan
proxmox_network_ethtool_disable_eee: true
proxmox_network_aspm_disable_enabled: false
proxmox_network_ethtool_ifaces:
  - "nic0"

# proxmox_template_debian13_vmid: 9000
# proxmox_template_debian13_name: "debian-13-template"
