swapfile_enabled: true
swapfile_backend: "zvol"
swapfile_zfs_dataset: "rpool/swap"
swapfile_path: "/dev/zvol/rpool/swap"
swapfile_size_mb: 4096
swapfile_swappiness: 25
swapfile_vfs_cache_pressure: 50
swapfile_force_recreate: true

zfs_arc_max_bytes: 2147483648

proxmox_network_enabled: true
proxmox_network_e1000e_mitigation_enabled: false
proxmox_network_cleanup_legacy_links: true
proxmox_network_ethtool_enabled: false
proxmox_network_ethtool_ifaces:
- "nic0"
proxmox_network_links:
- name: "nic0"
  mac: "f8:0d:ac:21:d2:a0"
  match:
    Type: "ether" # primary LAN trunk
- name: "wlp0"
  mac: "e8:4e:06:8f:b9:c0"
  match:
    Type: "wlan" # usb wifi
- name: "wlp1"
  mac: "d0:37:45:79:87:78"
  match:
    Type: "wlan" # usb wifi
proxmox_network_iface_manual:
- "nic0"
proxmox_network_bridge_blocks:
- name: "vmbr0"
  family: "inet"
  method: "static"
  auto: true
  address: "10.0.0.13/24"
  gateway: "10.0.0.1"
  options:
    bridge-ports: "nic0"
    bridge-stp: "off"
    bridge-fd: 0
    bridge-vlan-aware: "yes"
    bridge-vids: "10 20 30"
- name: "vmbr0.10"
  family: "inet"
  method: "static"
  auto: true
  address: "10.0.10.13/24"
  options:
    vlan-raw-device: "vmbr0"
    vlan-id: "10"
- name: "vmbr0.20"
  family: "inet"
  method: "static"
  auto: true
  address: "10.0.20.13/24"
  options:
    vlan-raw-device: "vmbr0"
    vlan-id: "20"
- name: "vmbr0.30"
  family: "inet"
  method: "static"
  auto: true
  address: "10.0.30.13/24"
  options:
    vlan-raw-device: "vmbr0"
    vlan-id: "30"

# proxmox_template_debian13_vmid: 9002
# proxmox_template_debian13_name: "debian-13-template"
