---
# SPDX-License-Identifier: MIT-0
galaxy_info:
  role_name: proxmox_template_debian13
  author: smeya
  description: Build and maintain a Debian 13 (Trixie) cloud-init VM template on Proxmox VE using qm and virt-customize
  company: m0sh1.cc

  license: MIT-0

  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - trixie

  galaxy_tags:
    - proxmox
    - cloudinit
    - debian
    - virtualization
    - template

dependencies: []
