galaxy_info:
  role_name: tailscale
  author: m0sh1
  description: Install and optionally configure Tailscale on Debian/Proxmox nodes
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags:
    - networking
    - vpn
    - tailscale

dependencies: []
