tailscale_authkey: "{{ tailscale_authkey_proxmox }}"
tailscale_enable_auto_up: true
tailscale_force_reauth: false
tailscale_router_enable: false

tailscale_up_extra_args: >
  --ssh=true
  --accept-dns=false
  --accept-routes=false
