apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps-limits.yaml
  - apps-quota.yaml
  - argocd-limits.yaml
  - argocd-quota.yaml
  - traefik-limits.yaml
  - traefik-quota.yaml
  - observability-limits.yaml
  - observability-quota.yaml
