apiVersion: v1
kind: LimitRange
metadata:
  name: traefik-limitrange
  namespace: traefik
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: 1Gi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
