apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apt-backend.yaml
  - dns01-backend.yaml
  - dns02-backend.yaml
  - pbs-01-backend.yaml
  # - pve-01-backend.yaml
  #- pve-02-backend.yaml
  - pdm-01-backend.yaml
  # - pve-scripts-backend.yaml
  - apt-ingress.yaml
  - dns01-ingress.yaml
  - dns02-ingress.yaml
  - pbs-01-ingress.yaml
  # - pve-01-ingress.yaml
  # - pve-02-ingress.yaml
  - pdm-01-ingress.yaml
  # - pve-scripts-ingress.yaml
