annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/semaphoreui/semaphore
    - name: Chart
      url: https://github.com/semaphoreui/charts/tree/main/stable/semaphore
  artifacthub.io/signKey: |
    fingerprint: 2B62F542C0C5614F8B4625AE0DDA0DEB51EF789C
    url: https://raw.githubusercontent.com/semaphoreui/charts/main/semaphore.key
apiVersion: v2
appVersion: 2.16.47
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 23.2.2
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.1.4
description: Modern UI and powerful API for Ansible, Terraform, OpenTofu, PowerShell
  and other DevOps tools
home: https://semaphoreui.com/
icon: https://raw.githubusercontent.com/semaphoreui/semaphore/develop/web/public/favicon.svg
keywords:
- ansible
- awx
- tower
- semaphore
maintainers:
- email: denis@semaphoreui.com
  name: Denis Gukov
  url: https://github.com/fiftin
name: semaphore
sources:
- https://github.com/semaphoreui/semaphore
type: application
version: 16.0.11
