apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAk8fM8XVheLwq7ZTxs2DQKj+RMf57yOulwHJ6h4ZDw8RVF8I+jIZAAbYl4iaD8vXpnbXcfmByhRBPxU2KnvypNrLh8FeflIe24S/jBKX57C9WMaDMp6qu7HFxvSDz2qUf05XL62IlNYicoZULFbopso1OdhryCOz10HdnllhUf50jFfp2Blyg49OPnGe7BrneKS4Y3zojNvyBzJopb1rZ0pK2BRn+7+Y8RxI7itsKBVZ2KXamCOYrm1Aftg4heYIJ4FenzoGGPlBlQwiOvDtjpJtACfNCUU+TDEKUML1i9XSEB4bG06rzUbsLWBHI2F2tke1gsHmUE8vpt77nMXcWpBAF1a5KWNntPHePrKXG2yGwta5YVLweGggu54jPDtpGpfLVNiic6KoAQV5pzTtMblFPRJPNNcayLDAPTuGHddMhVYxVQRmgvEDu21rTRdeTwG151WjrLKe39Ut+h1nNXmLob4CyWp8elMTyJvjkK9Si3ZOzn2OJyy/7Hd9SbKkYd+CER3FMwko+HC8/fWcNOEL6PsEzJjQGIY/xG8hs7OnhiAVtJzMSPZ/ZI0vJA3wGJrBbdAutFrZ/gZDCEmoSrxz5+egy/x64qix3p/99mXPbetMrgLt/cbHasOn+Q849IxRB8NQrHVmK6KF726TC5bGU0VgeotuYhtdXhwu7vGtrOqLQcY5T+sJOlyo1YSVHGcTUsHFg5wReh
    admin-user: AgCfDJqeD+Y9EhpjpUq+whO1USes56M8KjLQ6ZHSGuzgCMJwYkVppV7+UHB5jHVo/RFCqzayixKUqYAogmYlZuGGaH6qvQuWjbIcLv+bN94HSXJj9QWbGtJYkv7L/bJn1KyU3raylf6l3rBxOsIjYwo2otvWLqwHlhtoTlbgzxRxrBvmFdWsUcrsJfyTEu4OQv2Y6WiYdQqjZqnlT18RoqyOvqsxiAkdOogqIkHjaFd1LRynhLDTNrDC1V76sUVcCkCVNhfvRoK/+6/7AtbpOmrlSaDYKyP2RfCe17Cqg/LkCMKpp9bfcvTT+IGB2iecWMgE0a1LOqjSn4XRtGXHXLv/Mw4szHuG/A9V0sLKTV+vFtDhn5x1u4Y0zni25FwacmdBEitkUzbq7TMpI4x1bzKm3FKlkZ07dXPuh6TaPV7lt+L2cMM1ybTt3GOIeoin8Jc+veZxcahNRLQXU1RutUcFqJPYbNMaTbAkGTBkJNZP/smgHBe/RF37JRYZGfe3xxJruHLjd5d1pczufn6IuUQCTTm++k9DCMKJDYFcEbNvQxr8ZnXs8h8AARiBwo6Kd1kVZP7aAThJqTQnNllJsWYEZnX8mQcypTlzRvDDZoqFKxlJiE6FfILEev3op6wLFF0pB3iRHlh2oW1gOhU1ouDmCTJP/GO6AAlUywbh29g/Cp/uYV4kPoTKFzNhNmD6x+YM+a5X3g==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
