apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: observability
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: observability-prometheus-basicauth@kubernetescrd
    external-dns.alpha.kubernetes.io/hostname: prometheus.m0sh1.cc
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prometheus.m0sh1.cc
      secretName: wildcard-m0sh1-cc
  rules:
    - host: prometheus.m0sh1.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-prometheus
                port:
                  number: 9090
