# yaml-language-server: $schema=ignore
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-basicauth
  namespace: observability
spec:
  basicAuth:
    secret: prometheus-basic-auth
    removeHeader: true
