apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: observability
spec:
  encryptedData:
    users: AgA2CnNM/XJn4JFE9n6/bN+nuW5xMaClHDIEWkjT+F3411v84ItqCBiMwWTK4PYj3pVQEC6mOKAvqU4jTSlyxFePV5lX/3FtztEd4DrnhSkIua5RyTzc6B90tL9t+BB4mLmPPDt8dIC7qP//5+vRhUyQGrUEmf7L9KlgJUcLg2t0Ns4WLIp9JTzDRXO2lWmbGec5m89+ghAEXtTyecI/E0av0mGSr/V4r2ef3fvpPhlku2zgodxWnZrRUYX17Gl2pQUU59Fr9ofatlQSmOvWI7aPoXT5t4qm4pPkGPRXfnTqDNgUh0mm8ZrBxPujzXqeS0ICASMJsB8bhmPKfcmdtyXb8zNAZy6Rx0nYaGho3m8QlS59ySjSVEZ+J/L/jjBXayrkgnh/+eB+W4vrdnhC35UJelWBS5CUWV8Uy/yMdey70VqZfOsiD2niuCNf8Rh5VSwxWRrIu474z8cpDlTlPV6Tk7lhONRiMRK/y5Rv5Zw3H4X6SS9uc7ogXkOLtJvfqbLWn5dSyg1EqN3byBRNpB680cn4SCc2+FwouVg41Zr/KfPiOZ+20qCIuHz3szivvvWFWpJaBlIXCrjLGjZ74e7YNL3wGeXweN8KSsiuF/6XM6Cf9hCgdNf54qQLkuuQZxj/jPyZO1TRP7WxMrRtm5OWOM5GhmhOMRgIrK1cxLy2+7ptPsG7b2jwld43Y08NA9110dYTZm9A05TDViVBMjB6qWjU8l5iHbiNgiYrNgKUtaSr16XeXmDxlN4Z77AmEmUHb+UQyXJKqAs47nPWmM8ZN7FfQQ==
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: observability
    type: Opaque
