apiVersion: v1
kind: Service
metadata:
  name: pve-01-svc
  namespace: traefik
spec:
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pve-01-svc-1
  namespace: traefik
  labels:
    kubernetes.io/service-name: pve-01-svc
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "10.0.0.100"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-01
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pve-01.m0sh1.cc`)
      services:
        - name: pve-01-svc
          port: 8006
  tls:
    passthrough: true
