apiVersion: v1
kind: Service
metadata:
  name: pve-02-svc
  namespace: traefik
spec:
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pve-02-svc
  namespace: traefik
subsets:
  - addresses:
      - ip: 10.0.0.100
    ports:
      - name: https
        port: 8006
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-02
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pve-02.m0sh1.cc`)
      services:
        - name: pve-02-svc
          port: 8006
  tls:
    passthrough: true
