apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxmenux.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxmenux.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "proxmenux.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
