collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "12.2.0"
  - name: community.proxmox
    version: "1.5.0"
  - name: cloud.terraform
    version: "4.0.0"
