tailscale_authkey: "{{ tailscale_authkey_pdm }}"
tailscale_force_reauth: true
tailscale_enable_auto_up: true
tailscale_up_extra_args: >
  --ssh=true --accept-dns=false --accept-routes=false --advertise-tags=tag:pdm
