---
galaxy_info:
  author: Infrastructure Team
  description: Manage OPNsense firewall/router routine operations
  company: m0sh1.cc
  license: MIT
  min_ansible_version: "2.11"
  platforms:
    - name: FreeBSD
      versions:
        - all
  galaxy_tags:
    - opnsense
    - firewall
    - router
    - networking
    - freebsd

dependencies: []
