---
- name: Base setup on all lab nodes
  hosts:
    - pve_nodes
    - lxcs
    - k3s
    - pbs
  become: true

  vars_files:
    - ../inventory/group_vars/all/vault.yaml

  roles:
    - role: base
    - role: update_notifier
