apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-notifications-secret.sealedsecret.yaml
  - cloudflare-api-token.sealedsecret.yaml
  - cloudflared-tunnel-token.sealedsecret.yaml
  - cnpg-backup-credentials.sealedsecret.yaml
  - csi-proxmox.sealedsecret.yaml
  - external-dns-cloudflare.sealedsecret.yaml
  - minio-root-credentials.sealedsecret.yaml
  - monitoring-grafana-admin.sealedsecret.yaml
  - monitoring-grafana-mcp-api-key.sealedsecret.yaml
  - monitoring-loki-s3.sealedsecret.yaml
  - monitoring-prometheus-basic-auth.sealedsecret.yaml
  - monitoring-pve-exporter.sealedsecret.yaml
  - operator-oauth.sealedsecret.yaml
  - origin-ca-issuer-cloudflare.sealedsecret.yaml
  - repo-github-m0sh1-infra.sealedsecret.yaml
  - valkey-users.sealedsecret.yaml
  - kubernetes-dhi-pat.yaml
  - renovate-host-rules.sealedsecret.yaml
