---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgBt0ojFxsU0orB3TLxTSr4k9Zpxw2toZOWuX7gnJSQe9wztWczSQy4pLnqbPTbxKYvz/Vs+KV1cHMxFwQaE+l7uH6zuXY5eyCxlKPRDk0vRHBCGBzJtJtwUYVZChp7McKHEPMkT9oAEvYAMsQUHf8LJMLyt80RAUmV6RulCPp2YXu9z9U92/OoX8ctCu9Nx4lNcX/g9oaH6oHWa+vUU3wc4CwRmXRdAcKSnfeG2c4w/cfESYmMwxTikIKZxsLT8K1WEyQSckz8GKucpbL2jlf87MLlGg/uY5FpEqvbFUcrFJ+uTbBTrp+g8hDYT7+1IjgbCiMS8oBYy1pjcazoVmsi/0OTMIbiiv2QUGKDsijKGuaVsMLTkaPFfvz6TLE6mU7UxOXC6a7ghOExp7CuQOqfjkTSXE8iS0UVWSyY6sewOKOT62O5JSiaBRj5y0bdhrl5il1/S5rTSAQXabm+81X9Yuk9o5HoosCpwuHoIZMmiVaEJ/kRaIaHcya9oXzcUY9m4VLgaGqlFJ8zhDKY+RWcirukaiQ/59Jpv9ybIbU0/XhFdKb8bW3qRUnD1QZnXAXT5BIRf99JQneRRb4cnEEVfDxL+m9V0KuQnNTvP4pac/JQ4c2JIt5h7UtvHTUqgq22eMOqo/ttE3ix+eW2OT1sGHb+HrLNIQp0EqZwDH05HOqhRSeu/SMZw3/PeAyLYIzAo+y5Jke05qtDZyK++iaYa6UEU9GLTXJzXB9vvdqMhHWXSCEsQ0bf7B5ur1vGXcdlTDJnNMdd7LmesHtpLFItzRtDp3ssgnntDRyzeiqxt
  template:
    metadata:
      name: monitoring-prometheus-basic-auth
      namespace: monitoring
