k3s_service_name: "lab"
k3s_version: "v1.35.0+k3s1"
k3s_disable:
  - servicelb
  - coredns
k3s_server_tls_sans:
  - lab-ctrl.m0sh1.cc
  - lab-ctrl.xerus-nominal.ts.net
  - 10.0.0.201
  - 10.43.0.1
  - 127.0.0.1
  - ::1
  - 100.120.6.30
