apiVersion: v2
name: prometheus
description: Wrapper chart for kube-prometheus-stack (Prometheus Operator + Grafana + exporters)
type: application
version: 0.1.12
icon: https://prometheus.io/assets/prometheus_logo_grey.svg

dependencies:
  - name: kube-prometheus-stack
    version: 80.13.3
    repository: https://prometheus-community.github.io/helm-charts
