# SPDX-License-Identifier: MIT-0
galaxy_info:
  author: m0sh1
  description: eZFS helper CLI role for managing ZFS on Proxmox nodes
  company: m0sh1.cc

  license: MIT-0

  min_ansible_version: "2.15"

  galaxy_tags: []

dependencies: []
