apiVersion: traefik.io/v1alpha1
kind: TCPService
metadata:
  name: pbs-01-svc
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - address: "10.0.0.102:8007"
---
apiVersion: traefik.io/v1alpha1
kind: TCPRouter
metadata:
  name: pbs-01
  namespace: traefik
spec:
  entryPoints:
    - websecure
  rule: "HostSNI(`pbs-01.m0sh1.cc`)"
  service: pbs-01-svc
  tls:
    passthrough: true
