apiVersion: traefik.io/v1alpha1
kind: TCPService
metadata:
  name: pve-01-svc
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - address: "10.0.0.100:8006"
---
apiVersion: traefik.io/v1alpha1
kind: TCPRouter
metadata:
  name: pve-01
  namespace: traefik
spec:
  entryPoints:
    - websecure
  rule: "HostSNI(`pve-01.m0sh1.cc`)"
  service: pve-01-svc
  tls:
    passthrough: true
