apiVersion: traefik.io/v1alpha1
kind: TCPService
metadata:
  name: pve-02-svc
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - address: "10.0.0.101:8006"
---
apiVersion: traefik.io/v1alpha1
kind: TCPRouter
metadata:
  name: pve-02
  namespace: traefik
spec:
  entryPoints:
    - websecure
  rule: "HostSNI(`pve-02.m0sh1.cc`)"
  service: pve-02-svc
  tls:
    passthrough: true
