operator:
  image:
    repository: quay.io/minio/operator
    tag: v7.1.1@sha256:cd587f60c43dab75799370ad7b6c55f53cfa2188e85f4c5eda939591f8769f47
    pullPolicy: IfNotPresent

  # Install CRDs via the operator chart
  installCRDs: true

  # Keep defaults; only override if required
  env:
    - name: OPERATOR_STS_ENABLED
      value: "on"
