# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: m0sh1
  description: Install and configure apt-cacher-ng proxy cache
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
