apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-runner-01-config
  namespace: apps
  labels:
    app.kubernetes.io/name: semaphore-runner
    app.kubernetes.io/instance: semaphore
    app.kubernetes.io/component: runner
data:
  config.json: |
    {
      "tmp_path": "/tmp/semaphore",
      "web_host": "https://semaphore.m0sh1.cc:3000",
      "runner": {
        "token": "REPLACE_WITH_REGISTERED_TOKEN"
      }
    }
