apiVersion: v1
kind: ConfigMap
metadata:
  name: semaphore-runner-02-config
  namespace: apps
  labels:
    app.kubernetes.io/name: semaphore-runner
    app.kubernetes.io/instance: semaphore
    app.kubernetes.io/component: runner
data:
  config.json: |
    {
      "runner": {
        "api_url": "https://semaphore.m0sh1.cc/api",
        "max_parallel_tasks": 1
      }
    }
